### ISSUE TITLE
Add Rocket Launcher and Rockets

### ISSUE THREAD

**Issue by Alpha-thebaby** [Ultreon/pixel-guns#12]
### **Rocket Launcher Specifications:**

Ammunition Loading Type: Semi Automatic
Damage: 25.0
Range: 500
Fire Cooldown: 160
Magazine Size: 1
Ammunition: Rockets
Reload Cooldown: 160
Bullet Spread: 0.0
Recoil: 0.0
Pellet Count: 1
Loading Type: Individual
Reload Audio: TODO
Fire Audio: [attached]
Reload Cycles: 1
Is Scoped: false

**The model for the Rocket Launcher, Rockets, animation, SFX and Rocket icon are provided in the zip folder below.**
[rocket_launcher_assets.zip](https://github.com/Ultreon/pixel-guns/files/10308228/rocket_launcher_assets.zip)
[rpg main reload.zip](https://github.com/Ultreon/pixel-guns/files/10308261/rpg.main.reload.zip)

**Comment by Skylandia** [comment]
This needs a reload audio file.
It is to be noted that the firing audio is played when you fire the gun, and not when the rocket hits its target.
In my opinion, the firing audio should be trimmed down to be much shorter than it currently is to make it sound more "clean".
Obviously the rocket ammo item image needs some work too.

**Comment by Skylandia** [comment]
Main logic is added, small changes still need to be revised for the future, marking as closed.
