### ISSUE TITLE
Add Pump Shotgun

### ISSUE THREAD

**Issue by Alpha-thebaby** [Ultreon/pixel-guns#13]
### **Specifications:**

Ammunition Loading Type: Semi-Automatic
Damage: 18.0
Range: 25
Fire Cooldown: 5
Magazine Size: 5
Ammunition: Shotgun Shells
Reload Cooldown: 1
Bullet Spread: 0.4
Recoil: 0.0
Pellet Count: 5
Loading Type: Individual
Reload Cycles: 5
Is Scoped: false

[Pump shotgun Main.zip](https://github.com/Ultreon/pixel-guns/files/10303515/Pump.shotgun.Main.zip)
[Pump shotgun blueprint.zip](https://github.com/Ultreon/pixel-guns/files/10303565/Pump.shotgun.blueprint.zip)

**Comment by Skylandia** [comment]
Main logic has been added, still need to be provided with animations for a complete version. An issue can be made to update the animation. Marking as closed
