### ISSUE TITLE
Revamp Recoil

### ISSUE THREAD

**Issue by Alpha-thebaby** [Ultreon/pixel-guns#17]
Recoil should go up when fired and move down smoothly 

https://user-images.githubusercontent.com/115327854/209554694-81e6035d-572b-44d2-b3a5-4908014296c7.mp4

**Comment by Skylandia** [comment]
https://github.com/MrCrayfish/MrCrayfishGunMod/blob/1.19.X/src/main/java/com/mrcrayfish/guns/client/handler/RecoilHandler.java

**Comment by Alpha-thebaby** [comment]
Done

**Comment by Skylandia** [comment]
Not done. Please don't close issues you aren't working on.
