### ISSUE TITLE
Delay in shooting

### ISSUE THREAD

**Issue by Alpha-thebaby** [Ultreon/pixel-guns#24]
There is a delay when firing a weapon.

![image](https://user-images.githubusercontent.com/115327854/210117196-16741eb5-a3cc-4bf9-974c-4333d774c355.png)

**Comment by Skylandia** [comment]
Using a hacky fix at the moment, currently working on a long term fix but that may take some time.

**Comment by Alpha-thebaby** [comment]
Fixed in new patch
